#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Dec 17, 2018 01:59:46 PM +1100  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 395x261+773+246
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1062
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Ship Creation/Edit"
    vTcl:DefineAlias "$top" "Ship_Creator" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab45 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} -text {Name of Ship} 
    vTcl:DefineAlias "$top.lab45" "Label1" vTcl:WidgetProc "Ship_Creator" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Hitpoints 
    vTcl:DefineAlias "$top.lab46" "Label1_1" vTcl:WidgetProc "Ship_Creator" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text DPS 
    vTcl:DefineAlias "$top.lab47" "Label1_2" vTcl:WidgetProc "Ship_Creator" 1
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Range 
    vTcl:DefineAlias "$top.lab48" "Label1_3" vTcl:WidgetProc "Ship_Creator" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Speed 
    vTcl:DefineAlias "$top.lab49" "Label1_4" vTcl:WidgetProc "Ship_Creator" 1
    label $top.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Inertia 
    vTcl:DefineAlias "$top.lab50" "Label1_4" vTcl:WidgetProc "Ship_Creator" 1
    entry $top.ent51 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent51" "name" vTcl:WidgetProc "Ship_Creator" 1
    entry $top.ent52 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent52" "hitpoints" vTcl:WidgetProc "Ship_Creator" 1
    entry $top.ent53 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent53" "dps" vTcl:WidgetProc "Ship_Creator" 1
    entry $top.ent54 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent54" "range" vTcl:WidgetProc "Ship_Creator" 1
    entry $top.ent55 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent55" "speed" vTcl:WidgetProc "Ship_Creator" 1
    entry $top.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent56" "inertia" vTcl:WidgetProc "Ship_Creator" 1
    button $top.but57 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command Save -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Save 
    vTcl:DefineAlias "$top.but57" "SaveButton" vTcl:WidgetProc "Ship_Creator" 1
    button $top.but58 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command Save -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Cancel 
    vTcl:DefineAlias "$top.but58" "CancelButton" vTcl:WidgetProc "Ship_Creator" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 20 -y 40 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 20 -y 60 -width 78 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab47 \
        -in $top -x 20 -y 80 -width 78 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab48 \
        -in $top -x 20 -y 100 -width 78 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab49 \
        -in $top -x 20 -y 120 -width 78 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab50 \
        -in $top -x 20 -y 140 -width 78 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.ent51 \
        -in $top -x 110 -y 40 -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 110 -y 60 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent53 \
        -in $top -x 110 -y 80 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent54 \
        -in $top -x 110 -y 100 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent55 \
        -in $top -x 110 -y 120 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent56 \
        -in $top -x 110 -y 140 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.but57 \
        -in $top -x 40 -y 180 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 90 -y 180 -width 55 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

