#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 17, 2018 01:59:51 PM +1100  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True



def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Ship_Creator (root)
    #ShipCreator_support.init(root, top)
    root.mainloop()

w = None
def create_Ship_Creator(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Ship_Creator (w)
    #ShipCreator_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Ship_Creator():
    global w
    w.destroy()
    w = None

def handle_click(condition):
    print("Hi {}".format(condition))

class Ship_Creator:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 

        top.geometry("395x261+773+246")
        top.title("Shipfolder Creation/Edit")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.051, rely=0.153, height=21, width=78)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Name of Shipfolder''')

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.051, rely=0.23, height=21, width=78)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Hitpoints''')

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.051, rely=0.307, height=21, width=78)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#d9d9d9")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''DPS''')

        self.Label1_3 = tk.Label(top)
        self.Label1_3.place(relx=0.051, rely=0.383, height=21, width=78)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Range''')

        self.Label1_4 = tk.Label(top)
        self.Label1_4.place(relx=0.051, rely=0.46, height=21, width=78)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Speed''')

        self.Label1_4 = tk.Label(top)
        self.Label1_4.place(relx=0.051, rely=0.536, height=21, width=78)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Inertia''')

        self.name = tk.Entry(top)
        self.name.place(relx=0.278, rely=0.153,height=20, relwidth=0.415)
        self.name.configure(background="white")
        self.name.configure(disabledforeground="#a3a3a3")
        self.name.configure(font="TkFixedFont")
        self.name.configure(foreground="#000000")
        self.name.configure(insertbackground="black")

        self.hitpoints = tk.Entry(top)
        self.hitpoints.place(relx=0.278, rely=0.23,height=20, relwidth=0.415)
        self.hitpoints.configure(background="white")
        self.hitpoints.configure(disabledforeground="#a3a3a3")
        self.hitpoints.configure(font="TkFixedFont")
        self.hitpoints.configure(foreground="#000000")
        self.hitpoints.configure(highlightbackground="#d9d9d9")
        self.hitpoints.configure(highlightcolor="black")
        self.hitpoints.configure(insertbackground="black")
        self.hitpoints.configure(selectbackground="#c4c4c4")
        self.hitpoints.configure(selectforeground="black")

        self.dps = tk.Entry(top)
        self.dps.place(relx=0.278, rely=0.307,height=20, relwidth=0.415)
        self.dps.configure(background="white")
        self.dps.configure(disabledforeground="#a3a3a3")
        self.dps.configure(font="TkFixedFont")
        self.dps.configure(foreground="#000000")
        self.dps.configure(highlightbackground="#d9d9d9")
        self.dps.configure(highlightcolor="black")
        self.dps.configure(insertbackground="black")
        self.dps.configure(selectbackground="#c4c4c4")
        self.dps.configure(selectforeground="black")

        self.range = tk.Entry(top)
        self.range.place(relx=0.278, rely=0.383,height=20, relwidth=0.415)
        self.range.configure(background="white")
        self.range.configure(disabledforeground="#a3a3a3")
        self.range.configure(font="TkFixedFont")
        self.range.configure(foreground="#000000")
        self.range.configure(highlightbackground="#d9d9d9")
        self.range.configure(highlightcolor="black")
        self.range.configure(insertbackground="black")
        self.range.configure(selectbackground="#c4c4c4")
        self.range.configure(selectforeground="black")

        self.speed = tk.Entry(top)
        self.speed.place(relx=0.278, rely=0.46,height=20, relwidth=0.415)
        self.speed.configure(background="white")
        self.speed.configure(disabledforeground="#a3a3a3")
        self.speed.configure(font="TkFixedFont")
        self.speed.configure(foreground="#000000")
        self.speed.configure(highlightbackground="#d9d9d9")
        self.speed.configure(highlightcolor="black")
        self.speed.configure(insertbackground="black")
        self.speed.configure(selectbackground="#c4c4c4")
        self.speed.configure(selectforeground="black")

        self.inertia = tk.Entry(top)
        self.inertia.place(relx=0.278, rely=0.536,height=20, relwidth=0.415)
        self.inertia.configure(background="white")
        self.inertia.configure(disabledforeground="#a3a3a3")
        self.inertia.configure(font="TkFixedFont")
        self.inertia.configure(foreground="#000000")
        self.inertia.configure(highlightbackground="#d9d9d9")
        self.inertia.configure(highlightcolor="black")
        self.inertia.configure(insertbackground="black")
        self.inertia.configure(selectbackground="#c4c4c4")
        self.inertia.configure(selectforeground="black")

        self.SaveButton = tk.Button(top)
        self.SaveButton.place(relx=0.101, rely=0.69, height=24, width=35)
        self.SaveButton.configure(activebackground="#ececec")
        self.SaveButton.configure(activeforeground="#000000")
        self.SaveButton.configure(background="#d9d9d9")
        self.SaveButton.configure(disabledforeground="#a3a3a3")
        self.SaveButton.configure(foreground="#000000")
        self.SaveButton.configure(highlightbackground="#d9d9d9")
        self.SaveButton.configure(highlightcolor="black")
        self.SaveButton.configure(pady="0")
        self.SaveButton.configure(text='''Save''')

        self.CancelButton = tk.Button(top)
        self.CancelButton.place(relx=0.228, rely=0.69, height=24, width=55)
        self.CancelButton.configure(activebackground="#ececec")
        self.CancelButton.configure(activeforeground="#000000")
        self.CancelButton.configure(background="#d9d9d9")
        self.CancelButton.configure(disabledforeground="#a3a3a3")
        self.CancelButton.configure(foreground="#000000")
        self.CancelButton.configure(highlightbackground="#d9d9d9")
        self.CancelButton.configure(highlightcolor="black")
        self.CancelButton.configure(pady="0")
        self.CancelButton.configure(text='''Cancel''')
        self.CancelButton.configure(width=55)
        self.CancelButton.bind("<Button-1>", handle_click)

if __name__ == '__main__':
    vp_start_gui()





